config/routes.rb
Rails.application.routes.draw do
  get 'joins/create'

  get 'joins/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :update, :edit, :index]
  
  resources :events, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  resources :joins, only: [:create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: {maximum: 24}
  validates :content, presence: true, length: { maximum: 255 }
  # validates :image, presence: true
  validates :pick, presence: true
  # validates :term, presence: true
  validates :user_id, presence: true
  
  has_many :joins
  has_many :users, through: :ownerships
  has_many :goes
  has_many :go_users, through: :goes, class_name: 'User', source: :user
end

app/models/go.rb
class Go < Join
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: {message: "入力してください"}, length: { maximum: 50 }
  validates :email, presence: {message: "入力してください"}, length: {maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :events
  
  has_many :joins
  has_many :events, through: :joins
  has_many :goes 
  has_many :go_events, through: :goes, class_name: 'Event', source: :event
  
  
  def go(event)
    self.goes.find_or_create_by(event_id: event.id)
  end
  
  def ungo(event)
    go = self.goes.find_by(event_id: event.id)
    go.destroy if event
  end
  
  def go?(event)
    self.go_events.include?(event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private 
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def correct_user
    @event = current_user.events.find_by(id: params[:id])
    unless @event
      flash[:danger] = "権限がありません"
      redirect_to root_url
    
    end
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :destroy, :update]
  before_action :join_user_connect, only: [:join]
  
  
  
  def new
    @event = Event.new
    @word = "create"
  end

  def create
    @event = current_user.events.new(event_params)
    @event.term = Time.zone.local(params[:event]["term(1i)"].to_i,
                                  params[:event]["term(2i)"].to_i,
                                  params[:event]["term(3i)"].to_i,
                                  params[:event]["term(4i)"].to_i,
                                  params[:event]["term(5i)"].to_i)
    if @event.save
      flash[:success] = "イベントを作成しました"
      redirect_to @event
    else
      flash[:danger] = "イベントの作成に失敗しました"
      render 'new'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "イベントを削除しました"
    redirect_back(fallback_location: root_url)
  end

  def edit
    @event = Event.find(params[:id])
    @word = "Edit"
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = "イベントを編集しました"
      redirect_to @event
    else
      flash[:danger] = "編集に失敗しました"
      render :edit
    end
  end
  
  def index
    @events = Event.all.order('created_at DESC')
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  private
  
  def event_params
    params.require(:event).permit(:title, :content, :pick, :term)
  end
  
  def join_user_connect
    @event = current_user.events.find_by(params[:id])
    if @event
      flash[:dender] = "あなたは参加者です"
      redirect_to @event
    end
  end
  
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  def create
    @event = Event.find_or_initialize_by(id: params[:event_id])
    if params[:type] == "Go"
      current_user.go(@event)
      flash[:success] = "「#{@event.title}」に参加申請をしました"
    end
      redirect_back(fallback_location: root_path)
  end

  def destroy
    @event = Event.find(params[:event_id])
    if params[:type] == "Go"
      current_user.ungo(@event)
      flash[:success] = "「#{@event.title}」の参加をキャンセルしました"
    end
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました'
      redirect_to @user
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @event = current_user.events.build
      @events = current_user.events.order('created_at DESC').page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update]
  
  def show
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.all.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザーを登録しました'
      redirect_to @user
    else
      flash[:danger] = 'ユーザーの登録に失敗しました'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    if @user.valid? && params[:user][:password] == params[:user][:password_confirmation]
      @user.password = params[:user][:password]
      @user.save
      flash[:success] = 'ユーザー情報を編集しました'
      redirect_to @user
    else
      flash[:danger] = "ユーザー情報の登録に失敗しました"
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) 
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/events/_events.html.erb
<ul class="media-list col-sm-8">
  <% events.each do |event| %>
    <% user = event.user %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(user, options = { size: 100 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to user.name, user_path(user) %>
          <span class="text-muted">posted at <%= event.created_at %></span>
        </div>
        <%= link_to event do %>
        <div>
          <p><%= event.title %></p>
          <p><%= event.content %></p>
          <p><%= event.pick %></p>
          <p><%= event.term %></p>
        </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/events/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(event) do |f| %>
      <div class="form-group">
        <%= f.label :title, 'Title' %>
        <%= f.text_field :title, class: 'form-control', placeholder: "タイトルを入力してください" %>
      </div>
      <div class="form-group">
        <%= f.label :content, 'Content' %>
        <%= f.text_area :content, class: 'form-control', placeholder: "コンテンツを入力してください" %>
      </div>
      <div class="form-group">
        <%= f.label :pick, 'Pick' %>
        <%= f.select :pick, [["先着", "first"], ["抽選", "lottery"]], class: 'form-control bootstrap-date-only-width' %>
      </div>
      <div class="form-group">
        <%= f.label :term, 'Term' %>
        <%= f.datetime_select :term, class: 'form-control' %>
      </div>
      <%= f.submit word, class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<div class="text-center">
  <h1>Event Edit</h1>
</div>
<%= render 'form', event: @event, word: @word %>

app/views/events/index.html.erb
<div>
  <%= link_to "イベントを作成する", new_event_path, class: "btn btn-default btn-sm" %>  
</div>

<%= render 'events', events: @events %>

app/views/events/new.html.erb
<div class="text-center">
  <h1>Event Create</h1>
</div>
<%= render 'form', event: @event, word: @word %>

app/views/events/show.html.erb
<div>
  <h1><%= @event.title %></h1>
  <p><%= @event.content %></p>
  <%= @event.term %>
  <%= @event.pick %>  
</div>
<% if current_user == @event.user %>
  <%= link_to "Edit", edit_event_path(@event), class: "btn btn-primary btn-xs" %>
  <%= link_to "Delete", event_path(@event), method: "delete", data: {message: "Are you sure ?"}, class: "btn btn-danger btn-xs" %> 
<% else %>
  <div>
    <%= render 'joins/go_button', event: @event %>
  </div>
<% end %>


<div>
  <%= link_to '一覧へ戻る', events_path, class: "btn btn-default btn-sm" %>
</div>

app/views/joins/_go_button.html.erb
<% if current_user.go?(event) %>
  <%= form_tag(join_path(event.id), method: 'delete') do  %>
    <%= hidden_field_tag :event_id, event.id %>
    <%= hidden_field_tag :type, "Go" %>
    <%= submit_tag 'キャンセル', class: 'btn btn-success', data: {messege: "日程、内容をよく読んで参加してください。\n 参加しますか？ "} %>
  <% end %>
<% else %>
  <%= form_tag(joins_path) do %>
    <%= hidden_field_tag :event_id, event.id %>
    <%= hidden_field_tag :type, 'Go' %>
    <%= submit_tag '参加する', class: 'btn btn-primary', data: {message: "本当にキャンセルしますか？"} %>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">JoinEvents</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Events', events_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: 'delete' %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>JoinEvents</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログインユーザー: <%= current_user.name %></p>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the JoinEvents</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>Edit</h1>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit 'Edit', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users:@users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= @user.name %>
        </h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 120 }) %>" alt="">
        <p><%= link_to 'Edit', edit_user_path %></p>
      </div>
    </div>
  </aside>
  <div class="col-xs-10">
    <ul class="nav nav-tabs nav-justified">
      <li><a href="#">JoinEvents</a></li>
      <li><a href="#">Followings</a></li>
      <li><a href="#">Followers</a></li>
    </ul>
  </div>
</div>